redis:
  image: redis
node:
  image: starfox64/supinbot
  links:
    - redis:redis
  volumes:
    - /var/supinbot:/supinbot/shared
  environment:
    - SUPINBOT_REDIS_URI=redis://redis:6379
    - NODE_ENV=production
