version: '2'
services:
  node:
    image: starfox64/supinbot
    depends_on:
      - redis
    links:
      - redis:redis
    volumes:
      - /var/supinbot:/supinbot/shared
    environment:
      - SUPINBOT_REDIS_URI=redis://redis:6379
      - NODE_ENV=production
  redis:
    image: redis
